name: Deploy and Purge Cache

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🔨 Build Project
        run: |
          composer install --no-scripts
          cd wp-content/themes/startdigital
          npm install
          npm run build
          composer install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 27.54.133.107
          username: thestart
          password: ${{ secrets.DEV_FTP_PASS }}
          server-dir: public_html/staging/ # Make sure it ends in a trailing slash.
          # protocol: ftps # Required for some hosts.
